<script lang="ts">
  interface PaperSite {
    paper: string;
    path: string;
    title: string;
    generated: string;
    authors: string[];
    pdf_site: string;
    pdf_title: string;
    publication_date?: string;
  }

  export let data: { sites: PaperSite[] };

  // Format authors with Wikipedia links
  const formatAuthors = (authors?: string[]) => {
    if (!authors?.length || authors.every((a) => a === "Unknown author")) {
      return "Authors: Not specified";
    }

    return `Authors: ${authors
      .map((author) =>
        author !== "Unknown author"
          ? `<a href="https://scholar.google.com/scholar?q=${encodeURIComponent(author)}"
            target="_blank"
            rel="noopener"
            class="author-link">${author}</a>`
          : author,
      )
      .join(", ")}`;
  };
</script>

<div class="container">
  <header>
    <h1>Research Paper Explorer</h1>
    <p class="subtitle">Explore automatically generated paper analyses</p>
    <p class="explanation">
      This site serves as a research paper explorer, showcasing analyses of
      academic papers from the <a
        href="https://hobbsgroup.johnshopkins.edu/home.html"
        >Hobbs Energy-Environment Decisions Group</a
      >. These analyses are automatically generated by a Python script that
      utilizes the Gemini language model to translate the core ideas of a paper
      into interactive HTML pages. Inspired by the explanatory styles of Bret
      Victor and Bartosz Ciechanowski, the goal is to make complex concepts
      accessible through interactive visualizations and simulations. The source
      code for the generation script and the rest of this site can be found on
      <a
        href="https://github.com/paulhobbs/bhobbs-papers"
        target="_blank"
        rel="noopener">GitHub</a
      >.
    </p>
  </header>

  <div class="grid">
    {#each data.sites as site}
      <div class="card">
        <a href={site.path} class="paper-title" target="_blank" rel="noopener">
          {site.title}
        </a>
        <div class="date">
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
            <line x1="16" y1="2" x2="16" y2="6"></line>
            <line x1="8" y1="2" x2="8" y2="6"></line>
            <line x1="3" y1="10" x2="21" y2="10"></line>
          </svg>
          {site.publication_date}
        </div>
        <div>
          {@html formatAuthors(site.authors)}
        </div>
        <div style="font-size: 0.8rem">
          Paper: <a href="{site.pdf_site}">{site.pdf_title}</a>
        </div>
      </div>
    {/each}
  </div>
</div>

<style>
  :global(body) {
    font-family:
      system-ui,
      -apple-system,
      BlinkMacSystemFont,
      "Segoe UI",
      Roboto,
      Oxygen,
      Ubuntu,
      Cantarell,
      "Open Sans",
      "Helvetica Neue",
      sans-serif;
    background-color: #f8f9fa; /* Light grey background */
    color: #343a40; /* Darker base text color */
    margin: 0; /* Ensure no default body margin */
    padding: 0; /* Ensure no default body padding */
  }

  .container {
    max-width: 1140px; /* Slightly narrower */
    margin: 0 auto;
    padding: 3rem 1rem; /* More vertical padding */
  }

  header {
    text-align: center;
    margin-bottom: 4rem; /* More space below header */
  }

  h1 {
    font-size: 3rem; /* Slightly larger */
    font-weight: 700; /* Bolder */
    color: #212529; /* Slightly darker */
    margin-bottom: 1rem;
  }

  .subtitle {
    font-size: 1.2rem;
    color: #6c757d; /* Softer grey */
    margin-bottom: 1.5rem;
  }

  .explanation {
    max-width: 800px; /* Limit width for readability */
    margin: 0 auto 2rem auto; /* Center and add bottom margin */
    color: #495057; /* Slightly darker than subtitle */
    line-height: 1.6;
    font-size: 1rem;
  }

  .explanation a {
    color: #0056b3; /* Darker blue for links */
    text-decoration: none;
  }
  .explanation a:hover {
    text-decoration: underline;
  }

  .grid {
    display: grid;
    gap: 2rem; /* More gap */
    grid-template-columns: repeat(
      auto-fill,
      minmax(320px, 1fr)
    ); /* Slightly larger min width */
  }

  .card {
    background: #ffffff; /* Explicit white */
    border-radius: 12px; /* Softer corners */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05); /* Softer shadow */
    padding: 2rem; /* More padding */
    transition:
      transform 0.2s ease,
      box-shadow 0.2s ease;
    display: flex; /* Use flexbox for layout */
    flex-direction: column; /* Stack elements vertically */
    /* Removed justify-content: space-between; to let content flow naturally */
  }

  .card:hover {
    transform: translateY(-4px);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1); /* Slightly stronger hover shadow */
  }

  .paper-title {
    font-size: 1.2rem; /* Larger title */
    font-weight: 600; /* Bolder title */
    color: #0056b3; /* Darker blue */
    text-decoration: none;
    display: block;
    margin-bottom: 0.75rem; /* Reduced margin */
    line-height: 1.4;
  }

  .paper-title:hover {
    text-decoration: underline;
  }

  .date {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: #6c757d; /* Softer grey */
    font-size: 0.85rem; /* Slightly smaller */
    margin-bottom: 0.75rem; /* Space below date */
  }

  .date svg {
    flex-shrink: 0;
    color: #6c757d; /* Match text color */
    position: relative;
    top: -1px; /* Minor alignment tweak */
  }

  /* Style the author section directly */
  .card > div:last-child {
    /* Target the div containing authors */
    margin-top: auto; /* Push authors to the bottom if using flex space-between */
    padding-top: 1rem; /* Add space above authors if content is short */
    font-size: 0.9rem;
    color: #495057; /* Consistent text color */
    line-height: 1.5;
  }

  .author-link {
    color: #0056b3; /* Consistent link color */
    text-decoration: none;
  }

  .author-link:hover {
    text-decoration: underline;
  }

  .empty-state {
    text-align: center;
    padding: 4rem 1rem;
    color: #6c757d;
    background-color: #e9ecef; /* Light background for empty state */
    border-radius: 8px;
    margin-top: 2rem;
  }

  .empty-state svg {
    width: 56px; /* Slightly smaller */
    height: 56px;
    margin-bottom: 1rem;
    opacity: 0.7;
    color: #6c757d; /* Match text color */
  }

  .empty-state p {
    font-size: 1.1rem;
    margin: 0;
  }
</style>
