<script lang="ts">
  import { render } from "svelte/server";

  interface PaperSite {
    paper: string;
    path: string;
    title: string;
    generated: string;
    authors?: string[];
    publication_date?: string;
  }

  export let data: { sites?: PaperSite[] };

  // Format authors with Wikipedia links
  const formatAuthors = (authors?: string[]) => {
    if (!authors?.length || authors.every((a) => a === "Unknown author")) {
      return "Authors: Not specified";
    }

    return `Authors: ${authors
      .map((author) =>
        author !== "Unknown author"
          ? `<a href="https://scholar.google.com/scholar?q=${encodeURIComponent(author)}"
            target="_blank"
            rel="noopener"
            class="author-link">${author}</a>`
          : author,
      )
      .join(", ")}`;
  };
</script>

<div class="container">
  <header>
    <h1>Research Paper Explorer</h1>
    <p class="subtitle">Explore automatically generated paper analyses</p>
    <p class="explanation">
      This site serves as a research paper explorer, showcasing analyses of
      academic papers from the <a
      href="https://hobbsgroup.johnshopkins.edu/home.html" >Hobbs
      Energy-Environment Decisions Group</a >. These analyses are automatically
      generated by a Python script that utilizes the Gemini language model to
      translate the core ideas of a paper into interactive HTML pages. Inspired
      by the explanatory styles of Bret Victor and Bartosz Ciechanowski, the
      goal is to make complex concepts
      accessible through interactive visualizations and simulations. The source
      code for the generation script and the rest of this site can be found on
      <a
        href="https://github.com/paulhobbs/bhobbs-papers"
        target="_blank"
        rel="noopener">GitHub</a
      >.
    </p>
  </header>

  {#if data?.sites?.length}
    <div class="grid">
      {#each data.sites as site}
        <div class="card">
          <a
            href={site.path}
            class="paper-title"
            target="_blank"
            rel="noopener"
          >
            {site.title}
          </a>
          <div class="date">
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
              <line x1="16" y1="2" x2="16" y2="6"></line>
              <line x1="8" y1="2" x2="8" y2="6"></line>
              <line x1="3" y1="10" x2="21" y2="10"></line>
            </svg>
            {site.publication_date}
          </div>
          <div>
            {@html formatAuthors(site.authors)}
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="empty-state">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
      <p>No research papers available</p>
    </div>
  {/if}
</div>

<style>
  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem 1rem;
  }

  header {
    text-align: center;
    margin-bottom: 3rem;
  }

  h1 {
    font-size: 2.5rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
    color: #1a1a1a;
  }

  .subtitle {
    color: #666;
    font-size: 1.1rem;
    margin-bottom: 2rem;
  }

  .grid {
    display: grid;
    gap: 1.5rem;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  }

  .card {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    padding: 1.5rem;
    transition:
      transform 0.2s ease,
      box-shadow 0.2s ease;
  }

  .card:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.15);
  }

  .paper-title {
    font-size: 1.1rem;
    font-weight: 500;
    color: #0066cc;
    text-decoration: none;
    display: block;
    margin-bottom: 1rem;
  }

  .paper-title:hover {
    text-decoration: underline;
  }

  .date {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: #666;
    font-size: 0.9rem;
  }

  .date svg {
    flex-shrink: 0;
  }

  .metadata {
    margin-top: 1rem;
    font-size: 0.9rem;
  }

  .authors {
    color: #444;
    margin-bottom: 0.5rem;
  }

  .author-link {
    color: #0066cc;
    text-decoration: none;
  }

  .author-link:hover {
    text-decoration: underline;
  }

  .empty-state {
    text-align: center;
    padding: 4rem 0;
    color: #666;
  }

  .empty-state svg {
    width: 64px;
    height: 64px;
    margin-bottom: 1rem;
    opacity: 0.8;
  }
</style>
